[project]
name = "ecopt"
description = "ECOpt tunes hyperparameters for energy-efficiency and utility."
authors = [{name = "Emile Dos Santos Ferreira", email = "edsf2@cam.ac.uk"}]
requires-python = ">=3.10"
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "ax-platform>=0.4.3",
    "codecarbon>=2.8.1",
    "eco2ai>=0.3.10",
    "experiment-impact-tracker>=0.1.8"
]

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"
