[project]
name = "ecopt"
description = "ECOpt optimises hyperparameters for energy efficiency and utility."
requires-python = ">=3.10"
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "ax-platform>=0.4.3",
    "codecarbon==2.8.3",
    "mlflow>=2.20.1"
]

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"
